# **********************************************************************************************************************
# ApacheCXF property
# **********************************************************************************************************************
cxf:
  path: /Service


# **********************************************************************************************************************
# Kafka property
# **********************************************************************************************************************
spring:
  kafka:
    bootstrap-servers: localhost:9092

kafka:
  soap:
    topic:
      name: soapTopic

ftp:
  schedule:
    everyHourMF: 0 0 * * * MON-FRI


# **********************************************************************************************************************
# Swagger property
# **********************************************************************************************************************
springdoc:
  api-docs:
    path:
      /api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui-custom.html

folderUpload:
  file:
    pattern:Уралсиб_посещения(.*).xlsx